# Flutter Starter Kit - Analysis Options
# https://dart.dev/tools/analysis

analyzer:
  errors:
    non_constant_identifier_names: ignore
    constant_identifier_names: ignore

formatter:
  page_width: 120  # 한 줄 최대 길이 120자 설정

include: package:flutter_lints/flutter.yaml

linter:
  rules:
