# Flutter Starter Kit - Analysis Options
# https://dart.dev/tools/analysis

analyzer:
  errors:
    non_constant_identifier_names: ignore
    constant_identifier_names: ignore

formatter:
  page_width: 100

include: package:flutter_lints/flutter.yaml

linter:
  rules:
